### ISSUE TITLE
Name alias using 'as' keyword

### ISSUE THREAD

**Issue by assylman** [BreX900/index_generator#10]
Are there any possibilities to add name aliases for exported path?
Tried 
```
exports:
      - package: package:flutter/materials.dart
         as:
         - materials
```

but this is not the solution. Thanks
