### ISSUE TITLE
Is it possible to generate recursively indexes for nested folders ?

### ISSUE THREAD

**Issue by kristijorgji** [BreX900/index_generator#11]
Hi.

Let us assume we have the following folder structure

`lib/src/features`

The features folder can contain any number of features.
Example 

```
lib/src/features/home
lib/src/features/login
```

I want to find a way to configure this tool to build indexes automatically at every root folder under /features/
Example

`lib/src/features/home/home.dart`
This will export all the stuff defined under lib/src/features/home/presentation|data etc

The same should happen for 
`lib/src/features/login/login.dart`

**I don't know if this is possible and if yes how to configure it.**

At the moment, I can only export a library named `features` right now with the following config:

```
index_generator:
  exclude:
    - '**.part.dart'
    - '**.g.dart'
    - '**.freezed.dart'
  indexes:
    - path: lib/src/features
      include:
        - '**'
      name: features
      library: features

```
