### ISSUE TITLE
[Feature] Add option to add library level comment 

### ISSUE THREAD

**Issue by mdeandrea-mrmilu** [BreX900/index_generator#5]
When generate dart doc, is recommended add a [library-level doc commnet](https://dart.dev/guides/language/effective-dart/documentation#consider-writing-a-library-level-doc-comment).
This feature will be a nice option to have when generate index

**Comment by BreX900** [comment]
@mdeandrea-mrmilu I am undecided on how to call the names of the fields on the yaml file.

I would use `docs`, `doc`, `documentation` for comments to the library, then documentation with three `/`.
Instead I would use `comments` or `comment` for comments such as copyright, then those with two `/`.

Any suggestions? I also added the possibility of removing the disclaimer of the generation of the code

**Comment by mdeandrea-mrmilu** [comment]
I think that should be:

- docs: to add doc comment to index
- comments: to add simple comment to index
- disclaimer: enable/disable GENERATED CODE - DO NOT MODIFY BY HAND comment

So, the generated file will be:
```dart
// GENERATED CODE - DO NOT MODIFY BY HAND

// this is the line that comments property generate
// can has multiple lines

/// This is the line that documents property generate
/// Useful to document library
library example_index;
```
and the config to generate this:
```yaml
index_generator:
  indexes:
    - path: lib
      disclaimer: true (by default)
      comments: |
        this is the line that comments property generate
        can has multiple lines
      docs: |
        This is the line that documents property generate
        Useful to document library
```
